### ISSUE TITLE
Excellent!

### ISSUE THREAD

**Issue by AmyOlex** [WayGW/CCTR691#2]
Great work on creating your first Git Repository!  I noticed you have 2 README files.  One of the does not have the .md extension.  While not vital for this class, you generally want only 1 README file per directory.  If you are up for it you may delete the README that does not have an extension.  You can read how to do this cleanly here: https://docs.github.com/en/repositories/working-with-files/managing-files/deleting-files-in-a-repository

Please close this issue what you have read it.

**Comment by WayGW** [comment]
Okay, I read the link and used it to remove the extra README file that lacked the .md extension. Thank you for the information!
